openapi: 3.0.3
info:
  title: 'EAD ABTPé'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://new-abtpe.test'
paths:
  /api/v1/login:
    post:
      summary: ''
      operationId: postApiV1Login
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 254 characters.'
                  example: kjacobs@example.com
                password:
                  type: string
                  description: 'Must contain at least one uppercase and one lowercase letter; must contain at least one symbol; must contain at least one number.'
                  example: 'H3u3h#H%#ywQEG.'
                remember:
                  type: boolean
                  description: ''
                  example: true
              required:
                - email
                - password
      security: []
  /api/v1/register:
    post:
      summary: ''
      operationId: postApiV1Register
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: in
                email:
                  type: string
                  description: 'Must be a valid email address. Must not be greater than 254 characters.'
                  example: arunte@example.net
                password:
                  type: string
                  description: ''
                  example: deleniti
                password_confirmation:
                  type: string
                  description: ''
                  example: maiores
              required:
                - name
                - email
                - password
                - password_confirmation
      security: []
  /api/v1/logout:
    delete:
      summary: ''
      operationId: deleteApiV1Logout
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
  /api/v1/check-token:
    post:
      summary: ''
      operationId: postApiV1CheckToken
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Endpoints
  /api/v1/mzrt/users:
    get:
      summary: 'List all users'
      operationId: listAllUsers
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Mzrt
    post:
      summary: ''
      operationId: postApiV1MzrtUsers
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Mzrt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: deleniti
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: king.immanuel@example.com
                password:
                  type: string
                  description: ''
                  example: illum
                role:
                  type: string
                  description: 'Must be one of <code>development</code>, <code>superuser</code>, <code>admin</code>, <code>student</code>, or <code>instructor</code>.'
                  example: instructor
                address_id:
                  type: string
                  description: ''
                  example: null
                timezone_id:
                  type: string
                  description: ''
                  example: adipisci
                group_id:
                  type: string
                  description: ''
                  example: at
                document:
                  type: string
                  description: ''
                  example: error
                identity_registry:
                  type: string
                  description: ''
                  example: est
                avatar:
                  type: string
                  description: ''
                  example: null
                birth_date:
                  type: string
                  description: ''
                  example: consequatur
                gender:
                  type: string
                  description: ''
                  example: veritatis
                where_know_us:
                  type: string
                  description: ''
                  example: null
                source:
                  type: string
                  description: ''
                  example: facilis
                nickname:
                  type: string
                  description: ''
                  example: null
                commission:
                  type: string
                  description: ''
                  example: null
                bank_iban:
                  type: string
                  description: ''
                  example: null
                bank_name:
                  type: string
                  description: ''
                  example: null
                identify_image:
                  type: string
                  description: ''
                  example: null
                financial_approved:
                  type: string
                  description: ''
                  example: null
                available_meetings:
                  type: string
                  description: ''
                  example: null
                sex_meetings:
                  type: string
                  description: 'Must be one of <code>male</code>, <code>female</code>, or <code>both</code>.'
                  example: both
                meeting_type:
                  type: string
                  description: 'Must be one of <code>male</code>, <code>female</code>, or <code>both</code>.'
                  example: female
                active:
                  type: string
                  description: ''
                  example: ea
              required:
                - name
                - email
                - password
                - role
                - timezone_id
                - group_id
                - document
                - identity_registry
                - birth_date
                - gender
                - source
                - active
  '/api/v1/mzrt/users/{id}':
    get:
      summary: ''
      operationId: getApiV1MzrtUsersId
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Mzrt
    put:
      summary: ''
      operationId: putApiV1MzrtUsersId
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Mzrt
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: nihil
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: zulauf.emilio@example.org
                password:
                  type: string
                  description: ''
                  example: mollitia
                roles:
                  type: string
                  description: ''
                  example: sed
              required:
                - name
                - email
                - password
                - roles
    delete:
      summary: ''
      operationId: deleteApiV1MzrtUsersId
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Mzrt
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the user.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/mzrt/users/enable/{user_id}':
    patch:
      summary: ''
      operationId: patchApiV1MzrtUsersEnableUser_id
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Mzrt
    parameters:
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 1
        required: true
        schema:
          type: integer
  '/api/v1/mzrt/users/disable/{user_id}':
    patch:
      summary: ''
      operationId: patchApiV1MzrtUsersDisableUser_id
      description: ''
      parameters:
        -
          in: header
          name: Authorization
          description: ''
          example: 'Bearer {YOUR_AUTH_KEY}'
          schema:
            type: string
      responses: {  }
      tags:
        - Mzrt
    parameters:
      -
        in: path
        name: user_id
        description: 'The ID of the user.'
        example: 1
        required: true
        schema:
          type: integer
tags:
  -
    name: Endpoints
    description: ''
  -
    name: Mzrt
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: ''
security:
  -
    default: []
